name: Data Processing Assignment - Test Utility

on: 
  push: 
    branches: [ "main" ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build and run clean
      run: make clean; ./clean < wbcd.txt > cleaned_wbcd.txt

    - name: Upload clean Executable            
      uses: actions/upload-artifact@v4    
      with:
        name: clean            
        path: ./clean

    - name: Upload cleaned file           
      uses: actions/upload-artifact@v4    
      with:
        name: cleaned_wbcd.txt            
        path: ./cleaned_wbcd.txt

